
create table  projects (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  name varchar check (char_length(name) > 3),
  api_url varchar check (char_length(api_url) > 10),
  service_role_key varchar check (char_length(service_role_key) > 10),
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table projects enable row level security;
create policy "Individuals can create projects." on projects for
    insert with check (auth.uid() = user_id);
create policy "Individuals can view their own projects. " on projects for
    select using (auth.uid() = user_id);
create policy "Individuals can update their own projects." on projects for
    update using (auth.uid() = user_id);
create policy "Individuals can delete their own projects." on projects for
    delete using (auth.uid() = user_id);

