create table supacontent.content_types (
  id bigint generated by default as identity primary key,
  type text check (type  = any('{single, collection}' :: text[]) ),
  name text check (char_length(name) > 1),
  fields jsonb not null check (jsonb_array_length(fields)  >= 0),
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table supacontent.content_types enable row level security;


create or replace function supacontent.trfn_content_types_bu() returns trigger as $$
begin
  NEW.updated_at := clock_timestamp();
  raise debug 'Setting content_type.updated_at to %', NEW.updated_at::text;
  return NEW;
end;
$$ language plpgsql;

create or replace trigger tr_content_types_bu before update
    on supacontent.content_types
    for each row 
    execute function supacontent.trfn_content_types_bu();
