create table "yunocontent"."content_item_versions" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "data" jsonb,
    "content_item_id" bigint not null,
    "schema_id" bigint not null
);


alter table "yunocontent"."content_item_versions" enable row level security;

CREATE UNIQUE INDEX content_item_versions_pkey ON yunocontent.content_item_versions USING btree (id);

alter table "yunocontent"."content_item_versions" add constraint "content_item_versions_pkey" PRIMARY KEY using index "content_item_versions_pkey";

alter table "yunocontent"."content_item_versions" add constraint "content_item_versions_content_item_id_fkey" FOREIGN KEY (content_item_id) REFERENCES yunocontent.content_items(id) ON DELETE CASCADE not valid;

alter table "yunocontent"."content_item_versions" validate constraint "content_item_versions_content_item_id_fkey";

alter table "yunocontent"."content_item_versions" add constraint "content_item_versions_schema_id_fkey" FOREIGN KEY (schema_id) REFERENCES yunocontent.schemas(id) ON DELETE RESTRICT not valid;

alter table "yunocontent"."content_item_versions" validate constraint "content_item_versions_schema_id_fkey";

grant delete on table "yunocontent"."content_item_versions" to "anon";

grant insert on table "yunocontent"."content_item_versions" to "anon";

grant references on table "yunocontent"."content_item_versions" to "anon";

grant select on table "yunocontent"."content_item_versions" to "anon";

grant trigger on table "yunocontent"."content_item_versions" to "anon";

grant truncate on table "yunocontent"."content_item_versions" to "anon";

grant update on table "yunocontent"."content_item_versions" to "anon";

grant delete on table "yunocontent"."content_item_versions" to "authenticated";

grant insert on table "yunocontent"."content_item_versions" to "authenticated";

grant references on table "yunocontent"."content_item_versions" to "authenticated";

grant select on table "yunocontent"."content_item_versions" to "authenticated";

grant trigger on table "yunocontent"."content_item_versions" to "authenticated";

grant truncate on table "yunocontent"."content_item_versions" to "authenticated";

grant update on table "yunocontent"."content_item_versions" to "authenticated";

grant delete on table "yunocontent"."content_item_versions" to "service_role";

grant insert on table "yunocontent"."content_item_versions" to "service_role";

grant references on table "yunocontent"."content_item_versions" to "service_role";

grant select on table "yunocontent"."content_item_versions" to "service_role";

grant trigger on table "yunocontent"."content_item_versions" to "service_role";

grant truncate on table "yunocontent"."content_item_versions" to "service_role";

grant update on table "yunocontent"."content_item_versions" to "service_role";


