revoke delete on table "yunocontent"."content_authors" from "anon";

revoke insert on table "yunocontent"."content_authors" from "anon";

revoke references on table "yunocontent"."content_authors" from "anon";

revoke select on table "yunocontent"."content_authors" from "anon";

revoke trigger on table "yunocontent"."content_authors" from "anon";

revoke truncate on table "yunocontent"."content_authors" from "anon";

revoke update on table "yunocontent"."content_authors" from "anon";

revoke delete on table "yunocontent"."content_authors" from "authenticated";

revoke insert on table "yunocontent"."content_authors" from "authenticated";

revoke references on table "yunocontent"."content_authors" from "authenticated";

revoke select on table "yunocontent"."content_authors" from "authenticated";

revoke trigger on table "yunocontent"."content_authors" from "authenticated";

revoke truncate on table "yunocontent"."content_authors" from "authenticated";

revoke update on table "yunocontent"."content_authors" from "authenticated";

revoke delete on table "yunocontent"."content_authors" from "service_role";

revoke insert on table "yunocontent"."content_authors" from "service_role";

revoke references on table "yunocontent"."content_authors" from "service_role";

revoke select on table "yunocontent"."content_authors" from "service_role";

revoke trigger on table "yunocontent"."content_authors" from "service_role";

revoke truncate on table "yunocontent"."content_authors" from "service_role";

revoke update on table "yunocontent"."content_authors" from "service_role";

alter table "yunocontent"."content_authors" drop constraint "content_authors_author_id_fkey";

alter table "yunocontent"."content_authors" drop constraint "content_authors_pkey";

drop index if exists "yunocontent"."content_authors_pkey";

drop table "yunocontent"."content_authors";

create table "yunocontent"."content_items_authors" (
    "id" bigint generated by default as identity not null,
    "author_id" uuid not null,
    "content_id" uuid not null
);


alter table "yunocontent"."content_items_authors" enable row level security;

CREATE UNIQUE INDEX content_authors_pkey ON yunocontent.content_items_authors USING btree (id);

alter table "yunocontent"."content_items_authors" add constraint "content_authors_pkey" PRIMARY KEY using index "content_authors_pkey";

alter table "yunocontent"."content_items_authors" add constraint "content_authors_author_id_fkey" FOREIGN KEY (author_id) REFERENCES yunocontent.authors(id) ON DELETE CASCADE not valid;

alter table "yunocontent"."content_items_authors" validate constraint "content_authors_author_id_fkey";

grant delete on table "yunocontent"."content_items_authors" to "anon";

grant insert on table "yunocontent"."content_items_authors" to "anon";

grant references on table "yunocontent"."content_items_authors" to "anon";

grant select on table "yunocontent"."content_items_authors" to "anon";

grant trigger on table "yunocontent"."content_items_authors" to "anon";

grant truncate on table "yunocontent"."content_items_authors" to "anon";

grant update on table "yunocontent"."content_items_authors" to "anon";

grant delete on table "yunocontent"."content_items_authors" to "authenticated";

grant insert on table "yunocontent"."content_items_authors" to "authenticated";

grant references on table "yunocontent"."content_items_authors" to "authenticated";

grant select on table "yunocontent"."content_items_authors" to "authenticated";

grant trigger on table "yunocontent"."content_items_authors" to "authenticated";

grant truncate on table "yunocontent"."content_items_authors" to "authenticated";

grant update on table "yunocontent"."content_items_authors" to "authenticated";

grant delete on table "yunocontent"."content_items_authors" to "service_role";

grant insert on table "yunocontent"."content_items_authors" to "service_role";

grant references on table "yunocontent"."content_items_authors" to "service_role";

grant select on table "yunocontent"."content_items_authors" to "service_role";

grant trigger on table "yunocontent"."content_items_authors" to "service_role";

grant truncate on table "yunocontent"."content_items_authors" to "service_role";

grant update on table "yunocontent"."content_items_authors" to "service_role";


