create table supacontent.content_items (
  id bigint generated by default as identity primary key,
  content_type_id bigint references supacontent.content_types not null,
  user_id uuid references auth.users,
  data jsonb not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table supacontent.content_items enable row level security;