create table "public"."supabase_connections" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "refresh_token" text,
    "access_token" text,
    "expires_at" numeric
);


alter table "public"."supabase_connections" enable row level security;

CREATE UNIQUE INDEX connections_pkey ON public.supabase_connections USING btree (id);

alter table "public"."supabase_connections" add constraint "connections_pkey" PRIMARY KEY using index "connections_pkey";

alter table "public"."supabase_connections" add constraint "connections_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."supabase_connections" validate constraint "connections_user_id_fkey";

grant delete on table "public"."supabase_connections" to "anon";

grant insert on table "public"."supabase_connections" to "anon";

grant references on table "public"."supabase_connections" to "anon";

grant select on table "public"."supabase_connections" to "anon";

grant trigger on table "public"."supabase_connections" to "anon";

grant truncate on table "public"."supabase_connections" to "anon";

grant update on table "public"."supabase_connections" to "anon";

grant delete on table "public"."supabase_connections" to "authenticated";

grant insert on table "public"."supabase_connections" to "authenticated";

grant references on table "public"."supabase_connections" to "authenticated";

grant select on table "public"."supabase_connections" to "authenticated";

grant trigger on table "public"."supabase_connections" to "authenticated";

grant truncate on table "public"."supabase_connections" to "authenticated";

grant update on table "public"."supabase_connections" to "authenticated";

grant delete on table "public"."supabase_connections" to "service_role";

grant insert on table "public"."supabase_connections" to "service_role";

grant references on table "public"."supabase_connections" to "service_role";

grant select on table "public"."supabase_connections" to "service_role";

grant trigger on table "public"."supabase_connections" to "service_role";

grant truncate on table "public"."supabase_connections" to "service_role";

grant update on table "public"."supabase_connections" to "service_role";


create type "supacontent"."schema_type" as enum ('single', 'collection');

create type "supacontent"."supacontent.schema_type" as enum ('single', 'double');


