-- migrate:up

create table supacontent.content_types (
  id bigint generated by default as identity primary key,
  type varchar check (type  = any('{single, collection}' :: varchar[]) ),
  name varchar check (char_length(name) > 3),
  fields jsonb not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table supacontent.content_types enable row level security;


-- migrate:down

-- drop table

drop table supacontent.content_types cascade;