-- migrate:up

create table supacontent.content (
  id bigint generated by default as identity primary key,
  content_type_id bigint references supacontent.content_types not null,
  data jsonb not null,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table supacontent.content enable row level security;

-- migrate:down
drop table supacontent.content cascade;