create table "yunocommunity"."comments" (
    "id" bigint generated by default as identity not null,
    "content_item_id" bigint,
    "user_author_id" uuid default gen_random_uuid(),
    "parent_comment_id" bigint
);


alter table "yunocommunity"."comments" enable row level security;

create table "yunocommunity"."forums" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "deleted_at" timestamp with time zone,
    "archived_at" timestamp with time zone,
    "name" text not null,
    "description" text
);


alter table "yunocommunity"."forums" enable row level security;

create table "yunocommunity"."posts" (
    "id" bigint generated by default as identity not null,
    "content_item_id" bigint,
    "user_author_id" uuid default gen_random_uuid(),
    "forum_id" bigint,
    "multi_thread" boolean not null default false
);


alter table "yunocommunity"."posts" enable row level security;

CREATE UNIQUE INDEX comments_pkey ON yunocommunity.comments USING btree (id);

CREATE UNIQUE INDEX forums_pkey ON yunocommunity.forums USING btree (id);

CREATE UNIQUE INDEX posts_pkey ON yunocommunity.posts USING btree (id);

alter table "yunocommunity"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "yunocommunity"."forums" add constraint "forums_pkey" PRIMARY KEY using index "forums_pkey";

alter table "yunocommunity"."posts" add constraint "posts_pkey" PRIMARY KEY using index "posts_pkey";

alter table "yunocommunity"."comments" add constraint "comments_content_item_id_fkey" FOREIGN KEY (content_item_id) REFERENCES yunocontent.content_items(id) ON DELETE CASCADE not valid;

alter table "yunocommunity"."comments" validate constraint "comments_content_item_id_fkey";

alter table "yunocommunity"."comments" add constraint "comments_parent_comment_id_fkey" FOREIGN KEY (parent_comment_id) REFERENCES yunocommunity.comments(id) ON DELETE CASCADE not valid;

alter table "yunocommunity"."comments" validate constraint "comments_parent_comment_id_fkey";

alter table "yunocommunity"."comments" add constraint "comments_user_author_id_fkey" FOREIGN KEY (user_author_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "yunocommunity"."comments" validate constraint "comments_user_author_id_fkey";

alter table "yunocommunity"."posts" add constraint "posts_content_item_id_fkey" FOREIGN KEY (content_item_id) REFERENCES yunocontent.content_items(id) not valid;

alter table "yunocommunity"."posts" validate constraint "posts_content_item_id_fkey";

alter table "yunocommunity"."posts" add constraint "posts_forum_id_fkey" FOREIGN KEY (forum_id) REFERENCES yunocommunity.forums(id) ON DELETE RESTRICT not valid;

alter table "yunocommunity"."posts" validate constraint "posts_forum_id_fkey";

alter table "yunocommunity"."posts" add constraint "posts_user_author_id_fkey" FOREIGN KEY (user_author_id) REFERENCES auth.users(id) ON DELETE SET NULL not valid;

alter table "yunocommunity"."posts" validate constraint "posts_user_author_id_fkey";

grant delete on table "yunocommunity"."comments" to "anon";

grant insert on table "yunocommunity"."comments" to "anon";

grant references on table "yunocommunity"."comments" to "anon";

grant select on table "yunocommunity"."comments" to "anon";

grant trigger on table "yunocommunity"."comments" to "anon";

grant truncate on table "yunocommunity"."comments" to "anon";

grant update on table "yunocommunity"."comments" to "anon";

grant delete on table "yunocommunity"."comments" to "authenticated";

grant insert on table "yunocommunity"."comments" to "authenticated";

grant references on table "yunocommunity"."comments" to "authenticated";

grant select on table "yunocommunity"."comments" to "authenticated";

grant trigger on table "yunocommunity"."comments" to "authenticated";

grant truncate on table "yunocommunity"."comments" to "authenticated";

grant update on table "yunocommunity"."comments" to "authenticated";

grant delete on table "yunocommunity"."comments" to "service_role";

grant insert on table "yunocommunity"."comments" to "service_role";

grant references on table "yunocommunity"."comments" to "service_role";

grant select on table "yunocommunity"."comments" to "service_role";

grant trigger on table "yunocommunity"."comments" to "service_role";

grant truncate on table "yunocommunity"."comments" to "service_role";

grant update on table "yunocommunity"."comments" to "service_role";

grant delete on table "yunocommunity"."forums" to "anon";

grant insert on table "yunocommunity"."forums" to "anon";

grant references on table "yunocommunity"."forums" to "anon";

grant select on table "yunocommunity"."forums" to "anon";

grant trigger on table "yunocommunity"."forums" to "anon";

grant truncate on table "yunocommunity"."forums" to "anon";

grant update on table "yunocommunity"."forums" to "anon";

grant delete on table "yunocommunity"."forums" to "authenticated";

grant insert on table "yunocommunity"."forums" to "authenticated";

grant references on table "yunocommunity"."forums" to "authenticated";

grant select on table "yunocommunity"."forums" to "authenticated";

grant trigger on table "yunocommunity"."forums" to "authenticated";

grant truncate on table "yunocommunity"."forums" to "authenticated";

grant update on table "yunocommunity"."forums" to "authenticated";

grant delete on table "yunocommunity"."forums" to "service_role";

grant insert on table "yunocommunity"."forums" to "service_role";

grant references on table "yunocommunity"."forums" to "service_role";

grant select on table "yunocommunity"."forums" to "service_role";

grant trigger on table "yunocommunity"."forums" to "service_role";

grant truncate on table "yunocommunity"."forums" to "service_role";

grant update on table "yunocommunity"."forums" to "service_role";

grant delete on table "yunocommunity"."posts" to "anon";

grant insert on table "yunocommunity"."posts" to "anon";

grant references on table "yunocommunity"."posts" to "anon";

grant select on table "yunocommunity"."posts" to "anon";

grant trigger on table "yunocommunity"."posts" to "anon";

grant truncate on table "yunocommunity"."posts" to "anon";

grant update on table "yunocommunity"."posts" to "anon";

grant delete on table "yunocommunity"."posts" to "authenticated";

grant insert on table "yunocommunity"."posts" to "authenticated";

grant references on table "yunocommunity"."posts" to "authenticated";

grant select on table "yunocommunity"."posts" to "authenticated";

grant trigger on table "yunocommunity"."posts" to "authenticated";

grant truncate on table "yunocommunity"."posts" to "authenticated";

grant update on table "yunocommunity"."posts" to "authenticated";

grant delete on table "yunocommunity"."posts" to "service_role";

grant insert on table "yunocommunity"."posts" to "service_role";

grant references on table "yunocommunity"."posts" to "service_role";

grant select on table "yunocommunity"."posts" to "service_role";

grant trigger on table "yunocommunity"."posts" to "service_role";

grant truncate on table "yunocommunity"."posts" to "service_role";

grant update on table "yunocommunity"."posts" to "service_role";


