name: Build Check

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [app, web]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.9
          cache: npm
          cache-dependency-path: |
            app/package-lock.json
            web/package-lock.json

      - name: Install dependencies in ${{ matrix.dir }}
        working-directory: ${{ matrix.dir }}
        run: npm ci

      - name: Build ${{ matrix.dir }}
        working-directory: ${{ matrix.dir }}
        run: npm run build
