name: Deploy Web

on:
  workflow_dispatch:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash
    working-directory: web

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "22.9"
          cache: npm
          cache-dependency-path: '**/package-lock.json'
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-web-build-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies on web
        run: npm ci
      - name: Build web
        run: npm run build
      - name: Publish
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy build --project-name=yunokit-web --branch=${{ github.ref_name }}
          workingDirectory: web
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
