name: Remove Codex Label

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      - name: Remove codex label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: codex
