/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    "intro",
    "cli",
    {
      type: "category",
      label: "Features",
      collapsed: false,
      collapsible: false,
      items: [{ type: "autogenerated", dirName: "features" }],
      link: {
        type: "generated-index",
        description: "The main pluggable features of Supacontent",
      },
    },
    {
      type: "category",
      label: "Component Library",
      collapsed: false,
      collapsible: false,
      link: { type: "doc", id: "components/index" },
      items: [{ type: "autogenerated", dirName: "components/ui" }],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
